/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.cadastro;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import jopo.Planta;
import views.Principal;

/**
 *
 * @author Matheus Maia
 */
public class CadastroPlanta extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroPlanta
     */
    public CadastroPlanta() {
        initComponents();
    }
    Planta p = new Planta() {
    };
    Principal Principal = new Principal();
    private CadastroArbusto cadastroArbustos = null;
    private CadastroArvores cadastroArvores = null;
    private CadastroFlores cadastroFlores = null;

    public CadastroArbusto getCadastroArbustos() {
        return cadastroArbustos;
    }

    public void setCadastroArbustos(CadastroArbusto cadastroArbustos) {
        this.cadastroArbustos = cadastroArbustos;
    }

    public CadastroArvores getCadastroArvores() {
        return cadastroArvores;
    }

    public void setCadastroArvores(CadastroArvores cadastroArvores) {
        this.cadastroArvores = cadastroArvores;
    }

    public CadastroFlores getCadastroFlores() {
        return cadastroFlores;
    }

    public void setCadastroFlores(CadastroFlores cadastroFlores) {
        this.cadastroFlores = cadastroFlores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        porteField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();

        setTitle("Cdastre uma Planta");

        jLabel1.setText("Nome:");

        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });

        porteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porteFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Porte:");

        jLabel3.setText("Tipo:");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arbusto", "Arvores", "Flores" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Avançar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(porteField, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(comboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void openFrameInCenter(JInternalFrame jif) {
        Dimension desktopSize = Principal.getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    private void porteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porteFieldActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed

    }//GEN-LAST:event_comboTipoActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
        p.setNome(nomeField.getText());
        p.setPorte(porteField.getText());

        if (comboTipo.getSelectedItem() == "Arbusto" ) {
            if (cadastroArbustos == null || !cadastroArbustos.isDisplayable()) {
                cadastroArbustos = new CadastroArbusto();

            }
            cadastroArbustos.toFront();
        } else if (comboTipo.getSelectedItem().equals("Arvores")) {
            if (cadastroArbustos == null || !cadastroArbustos.isDisplayable()) {
            cadastroArvores = new CadastroArvores();
            Principal.add(cadastroArvores);
            this.openFrameInCenter(cadastroArvores);
        }
        cadastroArvores.toFront();
        } else if (comboTipo.getSelectedItem().equals("Flores")) {
            if (cadastroFlores == null || !cadastroFlores.isDisplayable()) {
            cadastroFlores = new CadastroFlores();
            Principal.add(cadastroFlores);
            this.openFrameInCenter(cadastroFlores);
        }
        cadastroFlores.toFront();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nomeField;
    private javax.swing.JTextField porteField;
    // End of variables declaration//GEN-END:variables
}
